### ISSUE TITLE
Warning and Error in HA 2024.11

### ISSUE THREAD

**Issue by TRIAG73** [Rsclub22/home-assistant-fht#6]
I get errors and warnings in the log file and my FHT-device does not show up.

any suggestions?

[FHT_2035](http://192.168.179.181:8083/fhem?detail=FHT_2035)

2024-11-14 17:47:09.662 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_HEAT was used from fht_heating, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'fht_heating' custom integration
2024-11-14 17:47:09.673 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_OFF was used from fht_heating, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'fht_heating' custom integration
2024-11-14 17:47:09.683 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from fht_heating, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'fht_heating' custom integration
2024-11-14 17:47:09.694 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from fht_heating, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'fht_heating' custom integration
2024-11-14 17:47:10.291 INFO (MainThread) [homeassistant.setup] Setting up climate
2024-11-14 17:47:10.295 INFO (MainThread) [homeassistant.setup] Setting up fht_heating
2024-11-14 17:47:10.315 INFO (MainThread) [homeassistant.setup] Setup of domain climate took 0.02 seconds
2024-11-14 17:47:10.318 INFO (MainThread) [homeassistant.setup] Setup of domain fht_heating took 0.02 seconds
2024-11-14 17:47:10.319 INFO (MainThread) [homeassistant.components.climate] Setting up fht_heating.climate
2024-11-14 17:47:10.352 ERROR (MainThread) [homeassistant.components.climate] Error while setting up fht_heating platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fht_heating/climate.py", line 35, in setup_platform
    _setup(hass, add_entities, config[ADDRESS], config[DEV_NAME])
  File "/config/custom_components/fht_heating/climate.py", line 44, in _setup
    dev.append(FhtDevice(address, dev_name))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fht_heating/climate.py", line 63, in __init__
    self.update()
  File "/config/custom_components/fht_heating/climate.py", line 100, in update
    self._fht_data_handler.get_value("desired-temp")
  File "/config/custom_components/fht_heating/fht.py", line 25, in get_value
    state = state.find("pre").text[-7:-1].replace(" ", "")
            ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

my configuration:

climate:
  - platform: fht_heating
    address: "192.168.179.181:8083"
    dev_name: "FHT_2035"

**Comment by Rsclub22** [comment]
sorry, i sadly do not have enough time to completely maintain this project, and also do not have enough time for the update, that is why this is not working. When i have time again, i will take a look. thanks for understanding

**Comment by haudouser** [comment]
Hi,
is there maybe an update in the next time ? Because it doesn't functions with HA 2025 !!!

**Comment by Rsclub22** [comment]
Sadly, as stated above i have not found time again. But Pull-Requests are welcome.

**Comment by Rsclub22** [comment]
Hi @haudouser and @TRIAG73 please try testing in the `devel` branch. Thx.
